language: generic
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -y doxygen python3 python3-yaml
  - ./travis/dependencies.sh
  - ./travis/setup.sh
script: make patch
after_success:
  - ./travis/deploy.sh
