language: generic
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
before_install:
  - sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade
  - sudo apt-get install -y doxygen python3 python3-yaml libstdc++6
  - ./travis/devkit.sh
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=$DEVKITPRO/devkitARM
  - export PATH=$PATH:$DEVKITARM/bin
  - ./travis/dependencies.sh
  - ./travis/setup.sh
script: make patch
after_success:
  - ./travis/deploy.sh
