language: generic
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -y doxygen python3 python3-yaml
  - ./travis/devkit.sh
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=$DEVKITPRO/devkitARM
  - export PATH=$PATH:$DEVKITARM/bin
  - ./travis/dependencies.sh
  - ./travis/setup.sh
script: make patch
after_success:
  - ./travis/deploy.sh
