language: generic
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -y doxygen gcc-arm-none-eabi python3
  - ./travis/dependencies.sh
  - ./travis/setup.sh
script: make patch
after_success:
  - ./travis/deploy.sh
